GET http://localhost:3000/api/customers

###

POST http://localhost:3000/api/customers
Content-Type: application/json

{
    "id": 2,
    "name": "Kinjal",
    "address": "Kolkata",
    "phone": "98765432103"
}

###

PUT http://localhost:3000/api/customers/2
Content-Type: application/json

{
    "address": "Kolkata25s"
}

###

DELETE http://localhost:3000/api/customers/2

###
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}